### ISSUE TITLE
"No Song Playing" when using Spotify Connect

### ISSUE THREAD

**Issue by chaddjohnson** [citruspi/Spotify-Notifications#116]
Hello! Thanks for the great software.

I noticed that "No Song Playing" shows in the notifications when changing songs while using Spotify Connect. When I switch back to playing on my MacBook, it once again shows the song titles in the notifications when switching songs.

**Comment by ergineroglu** [comment]
same for me when connected to chromecast

**Comment by PingWeb** [comment]
Same here!

**Comment by mijndert** [comment]
Same here.

**Comment by samarara** [comment]
Same!

**Comment by ThinkChaos** [comment]
This is a actually a bug in Spotify! Please comment and like [this issue](https://community.spotify.com/t5/Desktop-Mac/AppleScript-is-broken-when-using-Spotify-Connect/m-p/4897205) on their forums so that they fix it.

**Comment by ThinkChaos** [comment]
I also found [this thread](https://community.spotify.com/t5/Desktop-Mac/Bug-AppleScript-Spotify-Connect-Recent-update-broke-AppleScript/m-p/4778252), if you're down to also do the same there 😃

**Comment by chaddjohnson** [comment]
It appears this problem is fixed. I believe Spotify made some updates on their end that fixed this.

I'm marking this as closed.
