### ISSUE TITLE
Broken on macOS Catalina?

### ISSUE THREAD

**Issue by felker** [citruspi/Spotify-Notifications#118]
I know that this project hasn't been maintained for some years, but I was curious if anyone has this software working on macOS Catalina 10.15.3?

**Comment by vladserkoff** [comment]
Kind of. It only works if `Notify on play/pause` checkbox is set to true.

**Comment by felker** [comment]
Thanks, I got it working after reopening Spotify.

**Comment by 1n** [comment]
Maybe it will help someone.
After upgrade to Catalina I had to enable notifications for the Spotify Notifications app in MacOS Settings -> Notifications.
