### ISSUE TITLE
Add buttons for next song on notification hover.

### ISSUE THREAD

**Issue by tgpraveen** [citruspi/Spotify-Notifications#23]
IMHO this should be a useful, don't show buttons always but on hover on notification, it will be useful.

**Comment by sebj** [comment]
Notifications now have a skip button as of #56 being merged in! Thanks @tgpraveen  :)

**Comment by tgpraveen** [comment]
@sebj Thanks for implementing this :)

**Comment by sebj** [comment]
@tgpraveen No worries! 😃
