### ISSUE TITLE
[REQUEST] A setting to disable showing album artwork

### ISSUE THREAD

**Issue by AlexAbraham1** [citruspi/Spotify-Notifications#25]
First I would like to thank you for building this extension it is absolutely amazing! It's strange that Spotify doesn't have notification support built in and this is a perfect solution :-)

I am not sure if this is possible but if there could be a way to show the song name and album artwork when the popup notification is shown but not inside the notification center that would be great! The main issue is that it takes up too much space to show both in the notification center and I feel that it is a bit too cluttered.

Thanks!

Alex

**Comment by citruspi** [comment]
@AlexAbraham1,

I just wanted to give you an update. Yesterday I signed and published binaries for versions [0.5.0](https://github.com/citruspi/Spotify-Notifications/releases/tag/0.5.0) and [0.5.1](https://github.com/citruspi/Spotify-Notifications/releases/tag/0.5.1), so if you didn't build the project yourself, feel free to download the latest version.

&mdash; @citruspi
