### ISSUE TITLE
Multiple Displays

### ISSUE THREAD

**Issue by AndreSchwarzer** [citruspi/Spotify-Notifications#26]
Hi,

I like your application very much, but it'll be nice if you support multiple displays.

I currently run OS X 10.10 14A386b (latest public Beta) and the notification is always shown (even if not active) on the main display (with the Dock below).

╱╱┏╮
╱╱┃┃
▉━╯┗━╮
▉┈┈┈┈┃
▉╮┈┈┈┃
╱╰━━━╯

**Comment by sebj** [comment]
Just tested with the latest version (0.6.0) on macOS Sierra 10.12.1 and this no longer appears to be an issue. Feel free to comment if it still is.
