### ISSUE TITLE
Private area of the NSUserNotification API

### ISSUE THREAD

**Issue by fill1890** [citruspi/Spotify-Notifications#27]
Hi.

Just letting you know that the NSUserNotification has a Private subclass that allows a little more extensibility. It's not documented by Apple, but there's a short description at the end of [this](http://stackoverflow.com/questions/11676017/nsusernotification-not-showing-action-button) question, and the unofficial documentation is in [this](https://github.com/indragiek/NSUserNotificationPrivate) repo. 

This isn't really a good way if doing it, but you could find the extra features useful.

**Comment by sebj** [comment]
Used this in the pretty big #56 update, which is now merged into the repo. Thanks!
