### ISSUE TITLE
Notification Spotify-Icon Resolution

### ISSUE THREAD

**Issue by zvaehn** [citruspi/Spotify-Notifications#31]
Hey,
first of all: great work - i love it!

But the notification Spotify Icon seems to be in a low resolution and isn't even shown on my retina monitor. 

External monitor: http://cl.ly/image/1R18033d1V0l
Internal Retina monitor: http://cl.ly/image/0y051T2F071p

I saw, that you have already included a 512x512 icon in the iconset.
Can you have a look?

Sincerely, sven.

**Comment by sebj** [comment]
Just tested and this doesn't appear to be an issue with the latest version (0.6.0). Both album art and Spotify icon show fine on my Retina display. Feel free to comment if this is still an issue.
