### ISSUE TITLE
Spotify Icon not displaying on Notification

### ISSUE THREAD

**Issue by harrngtn** [citruspi/Spotify-Notifications#33]
I'm noticing that the spotify icon is not displayed in the notification popup (example image attached).  From left to right, the notification shows 
- Default Piece of Paper Icon
- Artist Information (Title, Album, Artist)
- Cover Art Icon.

So, everything looks correct, except for the left most icon, which shows as a default icon, rather then the spottily icon.
![notification](https://cloud.githubusercontent.com/assets/6288766/5236597/9348ed08-7807-11e4-8bad-a87ba99ba89f.jpg)

**Comment by sebj** [comment]
Seeing as there've been no updates on this issue in about 2 years, I'm closing it. Feel free to comment if the issue still occurs or there's an update.
