### ISSUE TITLE
Keyboard shortcut for showing currently playing song

### ISSUE THREAD

**Issue by gostaj** [citruspi/Spotify-Notifications#4]
(Thanks for a great notification app!)

Sometimes I listen to a good song which I don't know the name of.
I would like a keyboard shortcut for showing a notification, just like when a song starts, that shows the info about of the current song (just like the standard notification).
The keyboard shortcut doesn't change anything else, it just shows the notification.

And the keyboard shortcut should be GLOBAL (it shouldn't matter which application is focused) and editable.

**Comment by studgeek** [comment]
Note this only seems to be working when the preferences dialog is open. See #38.
