### ISSUE TITLE
Can't open distributable ZIP

### ISSUE THREAD

**Issue by SnarkNerd** [citruspi/Spotify-Notifications#40]
When trying to open the executable (downloaded from http://spotify-notifications.citruspi.io), I get the error:

“Spotify Notifications” is damaged and can’t be opened. You should move it to the Trash.

I'm on OS X Version 10.10.2, if it matters. Apologies if this is not the appropriate place to ask about this problem - the "Support" link on the dev site redirects to this GitHub.

**Comment by smctradeshift** [comment]
Same exact issue for me.

**Comment by ambervanos** [comment]
same, tried to download the new version of the plugin on OS X 10.10.2

**Comment by ambervanos** [comment]
You can download an earlier version from here: https://github.com/citruspi/Spotify-Notifications/releases . Untill the bug is fixed

**Comment by citruspi** [comment]
Hey,

Thanks for letting me know. I'm sorry to hear you're having this issue and I'm not sure what could be causing it.

The only time I've run into the 

> App is damaged and and can't be opened. You should move it to the Trash.

error is when the bundle has been modified after signing and Gatekeeper isn't happy.

Unfortunately, I don't have access to the computer which I use to archive and sign the application, but I can try re-signing it later today.

Would you be able to provide me with the output of

    $ codesign -dvvv /Applications/Spotify\ Notifications.app

and 

    $ tar -cvzf sn.tgz /Applications/Spotify\ Notifications.app && shasum -a 256 sn.tgz && rm sn.tgz

(Assuming the Spotify Notifications is in the `/Applications` directory. If not, just change the path).

Thanks!

&mdash; @citruspi

**Comment by rderharo** [comment]
Requested information:

```
codesign -dvvv /Applications/Spotify\ Notifications.app
Executable=/Applications/Spotify Notifications.app/Contents/MacOS/Spotify Notifications
Identifier=io.citruspi.Spotify-Notifications
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=717 flags=0x0(none) hashes=26+5 location=embedded
Hash type=sha1 size=20
CDHash=c7b692cd69ec04c8d31102908885736ca1c99dc3
Signature size=8521
Authority=Developer ID Application: Mihir Singh (SH52BQ2ZXA)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 22, 2015, 7:52:44 PM
Info.plist entries=24
TeamIdentifier=SH52BQ2ZXA
Sealed Resources version=2 rules=12 files=7
Internal requirements count=1 size=228
```

```
tar -cvzf sn.tgz /Applications/Spotify\ Notifications.app && shasum -a 256 sn.tgz && rm sn.tgz
tar: Removing leading '/' from member names
a Applications/Spotify Notifications.app
a Applications/Spotify Notifications.app/Contents
a Applications/Spotify Notifications.app/Contents/_CodeSignature
a Applications/Spotify Notifications.app/Contents/Info.plist
a Applications/Spotify Notifications.app/Contents/MacOS
a Applications/Spotify Notifications.app/Contents/PkgInfo
a Applications/Spotify Notifications.app/Contents/Resources
a Applications/Spotify Notifications.app/Contents/Resources/AppIcon.icns
a Applications/Spotify Notifications.app/Contents/Resources/en.lproj
a Applications/Spotify Notifications.app/Contents/Resources/status_bar_black.tiff
a Applications/Spotify Notifications.app/Contents/Resources/status_bar_colour.tiff
a Applications/Spotify Notifications.app/Contents/Resources/en.lproj/Credits.rtf
a Applications/Spotify Notifications.app/Contents/Resources/en.lproj/InfoPlist.strings
a Applications/Spotify Notifications.app/Contents/Resources/en.lproj/MainMenu.nib
a Applications/Spotify Notifications.app/Contents/MacOS/Spotify Notifications
a Applications/Spotify Notifications.app/Contents/_CodeSignature/CodeResources
cbda5bfc25bfff0448172e477d2647ed37147f3a272078ebe36deb054a81161e  sn.tgz
```

**Comment by Subastkar** [comment]
Having the same problem.
```
$ codesign -dvvv Spotify\ Notifications.app

Executable=/Users/alberto/Downloads/Spotify Notifications.app/Contents/MacOS/Spotify Notifications
Identifier=io.citruspi.Spotify-Notifications
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=717 flags=0x0(none) hashes=26+5 location=embedded
Hash type=sha1 size=20
CDHash=c7b692cd69ec04c8d31102908885736ca1c99dc3
Signature size=8521
Authority=Developer ID Application: Mihir Singh (SH52BQ2ZXA)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 22, 2015, 6:52:44 PM
Info.plist entries=24
TeamIdentifier=SH52BQ2ZXA
Sealed Resources version=2 rules=12 files=7
Internal requirements count=1 size=228

$ tar -cvzf sn.tgz Spotify\ Notifications.app && shasum -a 256 sn.tgz && rm sn.tgz

a Spotify Notifications.app
a Spotify Notifications.app/Contents
a Spotify Notifications.app/Contents/_CodeSignature
a Spotify Notifications.app/Contents/Info.plist
a Spotify Notifications.app/Contents/MacOS
a Spotify Notifications.app/Contents/PkgInfo
a Spotify Notifications.app/Contents/Resources
a Spotify Notifications.app/Contents/Resources/AppIcon.icns
a Spotify Notifications.app/Contents/Resources/en.lproj
a Spotify Notifications.app/Contents/Resources/status_bar_black.tiff
a Spotify Notifications.app/Contents/Resources/status_bar_colour.tiff
a Spotify Notifications.app/Contents/Resources/en.lproj/Credits.rtf
a Spotify Notifications.app/Contents/Resources/en.lproj/InfoPlist.strings
a Spotify Notifications.app/Contents/Resources/en.lproj/MainMenu.nib
a Spotify Notifications.app/Contents/MacOS/Spotify Notifications
a Spotify Notifications.app/Contents/_CodeSignature/CodeResources
17cd1c770ab8cd579378d33b140f1be9f50b6aa97bf281acd1498ab7b5bf6048  sn.tgz

**Comment by sammarcus** [comment]
Me as well, with 0.5.1, but based on the release page it seems you've made more recent commits to 0.5.0? Which is the most current version between the two?
    
    codesign -dvvv /Users/sammarcus/Downloads/Spotify\ Notifications.app 

    Executable=/Users/sammarcus/Downloads/Spotify Notifications.app/Contents/MacOS/Spotify Notifications
    Identifier=io.citruspi.Spotify-Notifications
    Format=bundle with Mach-O thin (x86_64)
    CodeDirectory v=20200 size=717 flags=0x0(none) hashes=26+5 location=embedded
    Hash type=sha1 size=20
    CDHash=c7b692cd69ec04c8d31102908885736ca1c99dc3
    Signature size=8521
    Authority=Developer ID Application: Mihir Singh (SH52BQ2ZXA)
    Authority=Developer ID Certification Authority
    Authority=Apple Root CA
    Timestamp=Feb 22, 2015, 7:52:44 PM
    Info.plist entries=24
    TeamIdentifier=SH52BQ2ZXA
    Sealed Resources version=2 rules=12 files=7
    Internal requirements count=1 size=228

![screen shot 2015-02-27 at 4 42 13 pm](https://cloud.githubusercontent.com/assets/8689264/6421971/c5baa296-bea1-11e4-8d0a-1dc4f0ef710c.png)

**Comment by citruspi** [comment]
@sammarcus,

I haven't made commits to 0.5.0 that are more recent than the commits to 0.5.1. It shows up higher on the Releases page because I tagged the 0.5.0 release after I tagged the 0.5.1 release.

&mdash; @citruspi

**Comment by sammarcus** [comment]
Whoops! My mistake, I apologize. I see what you're saying, sorry I overlooked that.
Anyways, I am running 0.5.0 with no problems 😊

**Comment by citruspi** [comment]
So, I'm not sure why some of you are having issues. I didn't have any problems, and I've talked to friends who have downloaded and ran it without issues.

I've re-archived, exported, and uploaded version 0.5.1, so feel free to try again and let me know how it goes.

For anyone using [cask](http://caskroom.io), it should work once [this pull request](https://github.com/caskroom/homebrew-cask/pull/9961) is merged in.

&mdash; @citruspi

**Comment by SnarkNerd** [comment]
For what it's worth, I could not open the previous one (I opened this issue), and I was able to download and open this one. Thanks very much, @citruspi ... have a great day.

**Comment by citruspi** [comment]
@SnarkNerd,

Awesome, glad to hear that!

I'm probably going to close this issue tomorrow if no one else reports still having the issue.

&mdash; @citruspi

**Comment by luisfrocha** [comment]
Same here. I was able to download and launch the app. Thanks!!

**Comment by rderharo** [comment]
Works for me as well. Thanks.

**Comment by sammarcus** [comment]
Is now working on my end. Thanks! 😊
