### ISSUE TITLE
Should be able to close notification

### ISSUE THREAD

**Issue by facundofarias** [citruspi/Spotify-Notifications#41]
Once the notification is shown, the user should be able to close it (with an X button, or something like that). Otherwise, if you need to use that part of the screen, for a few seconds it's "locked".

**Comment by citruspi** [comment]
@facundofarias,

I'm closing this as it's a duplicate of  #34.

&mdash; @citruspi

**Comment by facundofarias** [comment]
Yeah, sorry I did a quick search and I didn't find it (or I was too sleepy).
Thanks
