### ISSUE TITLE
Spotify Notifications is damaged

### ISSUE THREAD

**Issue by ttmjason** [citruspi/Spotify-Notifications#42]
I'm getting this error message, even after I delete it and try downloading a new version:

"“Spotify Notifications.app” is damaged and can’t be opened. You should move it to the Trash."

I'm on OSX Yosemite 10.10.1, late 2012 Mac Mini.

**Comment by citruspi** [comment]
@ttmjason,

This is a duplicate of #40.

&mdash; @citruspi
