### ISSUE TITLE
Show current song only works when on preferences panel

### ISSUE THREAD

**Issue by amandapinsker** [citruspi/Spotify-Notifications#45]

**Comment by citruspi** [comment]
Hey, thanks for filling an issue. Would you be able to elaborate a little? I'm not sure what the problem is.

**Comment by vogler** [comment]
Same as #38.

**Comment by BartHuis** [comment]
@citruspi  its not the same as #38 , i have this problem too. i assigned F19 on my mac keyboard to the "show current song playing" action, when i press it when the preferences pane is active, it shows it correctly, but when i switch to an other program, and then press F19, it doesn't show up also...

**Comment by razvan-tudosa** [comment]
This functionality is not working for me either. My custom shortcut only works if the Spotify Notification Options panel is on my screen.

**Comment by citruspi** [comment]
This issue has been fixed in #56.
