### ISSUE TITLE
"Run on Startup" preference causes Spotify to run on login, not Spotify Notifications

### ISSUE THREAD

**Issue by swrobel** [citruspi/Spotify-Notifications#49]
Changing the "Run on Startup" preference to "Enabled" causes Spotify to be added toSystem Preferences > Users & Groups > Login Items rather than Spotify Notifications. This occurs on El Capitan beta - I don't have another version of OS X to test on.

**Comment by studgeek** [comment]
It seems to properly add Spotify Notifications for me on 10.10.4

**Comment by sebj** [comment]
Can't replicate this on the final build of El Capitan – perhaps this should be closed?

**Comment by swrobel** [comment]
On OSX 10.11

![Screencast](http://g.recordit.co/CGAL4RflLP.gif)

**Comment by citruspi** [comment]
So, for a moment I thought it was an actual bug, but then....

![spotify notifications login item](https://cloud.githubusercontent.com/assets/2125849/10376508/2cec08d6-6dcc-11e5-90fd-fa801ebaebbf.gif)

**Comment by swrobel** [comment]
Dear god, I am an idiot. I'm terribly sorry.
