### ISSUE TITLE
Move Spotify to Menu Bar

### ISSUE THREAD

**Issue by RowanKaag** [citruspi/Spotify-Notifications#53]
Could this little app remove Spotify (even when running) from the Dock and be 'minimized' into the menu bar, like 'Spotify Notifications' is by default? Then when clicking the menu item, become maximized again?

label: feature request

**Comment by citruspi** [comment]
Hey, @RowanKaag, unfortunately I don't think this is something I would add to Spotify Notifications.

While I'm aware that you can modify an OS X application's information property list file to hide the application's icon from the Dock, I don't believe that it's a feature that belongs in Spotify Notifications itself.

I think that editing Spotify's information property list file and then providing a menu item to access Spotify would be feature creep.

If you disagree, you're welcome to re-open the issue and let me know your thoughts.

**Comment by RowanKaag** [comment]
Thank you for your thoughts. 

While I agree that it wouldn't belong to 'Spotify Notifications', I don't see a reason not to include it when possibly adding more functions that go out of the scope of just the notification implementation. But obviously, that is completely up to you whether you want to go beyond that or not. Anyhow, I would definitely be using that other app (as well) if it has some nifty features. 

For now, I will be hiding the Dock icon like you said (thank you) and control Spotify via spot_mini for Alfred 2. Not the ideal solution, but will be thinking of something else. 

Thank you for your time :)

**Comment by citruspi** [comment]
So, I could see adding a menu item to open Spotify.

Then users could edit Spotify's information property list file themselves if they'd like to _only_ access Spotify through there.

Would that be fine. And should the item be named `Spotify` or `Open Spotify`?

**Comment by RowanKaag** [comment]
That'd be awesome!

**Comment by sebj** [comment]
As of #56 being merged in, there's a menubar item to open Spotify. Thanks for your idea @RowanKaag! :)
