### ISSUE TITLE
Enhancement - Add custom styling

### ISSUE THREAD

**Issue by simeg** [citruspi/Spotify-Notifications#57]
I'd really like to have the option to re-style the notification pop-up, but unfortunately I cant write Swift or Objective-C. Personally I'd like a darker theme and a slimmer pop-up.

Thanks for the great work.

**Comment by citruspi** [comment]
Hey @simeg, as far as I'm aware, OS X Notification Center notifications cannot be styled.

The most "customization" that OS X will allow you is this:

<img width="378" alt="screen shot 2015-10-11 at 4 44 21 pm" src="https://cloud.githubusercontent.com/assets/2125849/10418981/60e6bf7e-7037-11e5-988d-e1e80009a954.png">

I believe that you can style [Growl][Growl] notifications using CSS, but Spotify Notifications just uses OS X Notification Center.

To be honest, I'm not sure if I'm interested in adding (and maintaining) support for Growl when the majority of OS X users I've talked to are content with OS X Notification Center.

[Growl]: http://growl.info
