### ISSUE TITLE
Growl

### ISSUE THREAD

**Issue by atb69** [citruspi/Spotify-Notifications#60]
Hi, any plans to incorporate Growl support in the future? Thanks!

**Comment by sebj** [comment]
Seems unlikely seeing as Growl is pretty much unused and replaced by notification centre, and the minimum macOS target will only get higher for the project as time goes on. @citruspi thoughts?

**Comment by citruspi** [comment]
Yup, I'd probably agree with @sebj. If Growl had a significant market share, I might reconsider, but I'd be surprised if that was the case.

It certainly wouldn't allow us to support older macOS releases -  Spotify currently requires macOS 10.9 or later and the macOS Notification Center was released as part of macOS 10.8 - any Spotify (and Spotify Notifications) users should have Notification Center available.
