### ISSUE TITLE
Request: White icon for OS X Dark Mode users

### ISSUE THREAD

**Issue by jadchaar** [citruspi/Spotify-Notifications#61]
Currently, there are menu bar icon options of coloured, black, and none. Anyway we can get a white version for dark mode users? Thanks!

**Comment by TheSeg** [comment]
When you select 'black', it detects dark mode and automatically switches to a white icon.

Course, one could say 'black' as the label of the option isn't intuitive. Perhaps renaming to 'auto' or 'standard'?

**Comment by jadchaar** [comment]
I think maybe doing "Auto (Black/White)" may be the best choice. Also, I think ya'll should default that over colored because a lot of menu bar icons are black and white :).
