### ISSUE TITLE
keyboard shortcut not working

### ISSUE THREAD

**Issue by madkap** [citruspi/Spotify-Notifications#62]
running mac osx 10.10.5, app ver 0.5.2

i set the shortcut to view current song but can't use the shortcut outside of the spotify-notifications app. Don't know if it's a known issue, couldn't find a related issue. Thanks.

**Comment by J0HAN85** [comment]
Same here, except I'm running OS X 10.11.4
It did work for me in the past.

**Comment by J0HAN85** [comment]
I just figured out that it's working again when I set "Show only current song" to disabled.

**Comment by rgbink** [comment]
@J0HAN85 Any idea as to why? What does "Show only current song" do, actually? What other song would notification show?

**Comment by J0HAN85** [comment]
@rgbink Nope, I have no idea what is does or means.

**Comment by nbgraham** [comment]
I had the same issue on MacOS Sierra Version 10.12 (16A323).

Disabling "Show only current song" also worked for me.

**Comment by citruspi** [comment]
This issue has been fixed in #56.
