### ISSUE TITLE
Request: Change "Disable when Spotify has Focus"

### ISSUE THREAD

**Issue by tannerpreiss** [citruspi/Spotify-Notifications#64]
Just a little user feedback, the "Disable when Spotify has Focus" options are not clear.

For instance: 
- `Disable when Spotify has Focus = Enabled.`
  Is this saying when spotify has focus the notifications are disabled? or is this saying when the spotify has focus the notifications or enabled? 
- It is similar to `False when Spotify has Focus` --> `True or False`. Clearly this makes no sense.

I don't have a strong recommendation for the new wording but having the world Disable in the text and then the options are enabled or disabled, seems strange.

btw. sick app i use it on all my macs.

**Comment by sebj** [comment]
Could reword a couple of the notifications preferences options to something similar to this:

![](https://cloud.githubusercontent.com/assets/379991/21588919/818b6190-d0e3-11e6-8559-dc719321eb41.png)

Edit: Have done so in `swift-dev` branch, coming soon to a release near you.
