### ISSUE TITLE
Updated icon

### ISSUE THREAD

**Issue by mike-u** [citruspi/Spotify-Notifications#68]
It would be nice to update the icon to the new color. I'm having trouble finding where the current one is stored in this project though.

**Comment by nbgraham** [comment]
Which icon are you talking about? The app icons are identical colors.

![same colors](https://cloud.githubusercontent.com/assets/11163850/18792856/ccd52966-817d-11e6-91ce-c17b255e4190.png)

**Comment by mike-u** [comment]
I see I was just on an older version, sorry.
