### ISSUE TITLE
"Show Current Song" shortcut doesn't work when other apps have focus

### ISSUE THREAD

**Issue by nbgraham** [citruspi/Spotify-Notifications#69]
As far as I can tell, the "Show Current Song" shortcut only works when I have the preferences open and in focus. If I close the preferences or switch focus to another app like Chrome, XCode,  or Terminal, the shortcut does nothing.

I tried with:
- ⌥⇧⌘E
    - option shift command E
- ⌥⌘s
    - option command S

**Comment by OstrichProjects** [comment]
Same here on macOS Sierra 10.12 (16A323)

**Comment by nbgraham** [comment]
Duplicate of
* #38 Notification banners not functioning
* #62 keyboard shortcut not working
