### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by RowanKaag** [citruspi/Spotify-Notifications#72]
Could anyone provide build instructions? I'm rather new to XCode and the version on https://spotify-notifications.citruspi.io is outdated, nor are there release provided on GitHub.

Thank you in advance!

**Comment by citruspi** [comment]
Once you've got Xcode installed, run

```
git clone --recursive git@github.com:citruspi/Spotify-Notifications.git
```

to clone the repository and the git submodules.

Open the `Spotify-Notifications.xcodeproj` file in Xcode, and then in the menu do `Product > Archive`.

Hit `Export` on the right and then select `Export as a macOS App` unless you've got a Developer Account setup.

<img width="100%" alt="untitled" src="https://cloud.githubusercontent.com/assets/2125849/19447162/da8024e8-9461-11e6-891c-577f04d08b2a.png">

I'm currently traveling and the MacBook I have with me doesn't have my Developer Account set up, but I should be able to build a signed copy and update the website later this week once I get back home.

Until then, here's an unsigned copy in case you can't get the Xcode build running - 
[Spotify Notifications 2016-10-17 12-00-32.zip](https://github.com/citruspi/Spotify-Notifications/files/534189/Spotify.Notifications.2016-10-17.12-00-32.zip)

**Comment by RowanKaag** [comment]
Thank you, building worked out. I kept getting 'Test' which presumably came from MASShortcut. Changed the 'Product > Scheme' to Spotify-Notifications, working as intended :)

**Comment by RowanKaag** [comment]
#53 is working perfectly, thank you so much. Will be posting a video later today.

**Comment by RowanKaag** [comment]
What's not immediately clear in the video is that my Spotify window is hidden in the background through changing the LSUIElement. By opening it either through Spotify Notifications or Alfred, it brings up the **hidden** window.

https://www.youtube.com/watch?v=0GFlWA_hZa0

**Comment by RowanKaag** [comment]
I can imagine others wanting these instructions. Would it be an idea to incorporate these in the readme.md or make a document like building.md and referende it in the readme?

**Comment by sebj** [comment]
Depends on your knowledge of building an app from source, to me at least this all seems pretty familiar stuff. We need to provide the latest release on Github anyway, and that should be fine for most people.

**Comment by citruspi** [comment]
> Depends on your knowledge of building an app from source, to me at least this all seems pretty familiar stuff.

Yeah, I'd agree with that. In general I don't think that the build process for the application is esoteric - it's fairly standard for any macOS or iOS application. Clone the repository (and any dependencies) and then create an archive.

If we provided build instructions, they'd probably look like this:

> Clone the repository using
> ```
> git clone --recursive git@github.com:citruspi/Spotify-Notifications.git
> ```
> and then build a release.

I may look into creating a Makefile which leverages `xcodebuild` to build the application for you, but that isn't very high on my to do list to be honest.

> We need to provide the latest release on Github as a pre-built download anyway,

Yep, agreed. I was originally supposed to fly back home tonight but my flight was delayed and then moved to tomorrow. Assuming I actually make it back home tomorrow, I should hopefully be able to upload a signed release tomorrow night.

**Comment by citruspi** [comment]
Another item that's not very high on my to do list, but I might try to setup a spare MacBook as an Xcode build server to perform CI and automatically sign and distribute archives.

And then ideally, merge to master would automatically result in a new archive being built, signed, and uploaded and the website being re-built.

**Comment by RowanKaag** [comment]
Sounds great, thank you!

**Comment by citruspi** [comment]
Forgot to update the issue, but I cut a [release][0] last weekend and updated the [website][1] with version 0.6.0.

[0]: https://github.com/citruspi/Spotify-Notifications/releases/tag/0.6.0
[1]: https://spotify-notifications.citruspi.io
