### ISSUE TITLE
Home Page Down

### ISSUE THREAD

**Issue by purevertigo** [citruspi/Spotify-Notifications#76]
How do I install this? Your website is down and I can't find any installation instructions.

**Comment by citruspi** [comment]
Hey, sorry, DNS issue.

I'm currently at the airport waiting to board a flight, but I think it should be resolved by the time I land. If it isn't, I'll take another look.

Sorry about that.

**Comment by citruspi** [comment]
Looks like it's been resolved, feel free to re-open the issue if you continue to experience problems.
