### ISSUE TITLE
How to remove Spotify icon?

### ISSUE THREAD

**Issue by rpanachi** [citruspi/Spotify-Notifications#78]
There is a way to remove the Spotify icon (the green logo) from notification?

<img width="375" alt="screenshot 2016-12-07 21 47 46" src="https://cloud.githubusercontent.com/assets/51511/20991692/e163d092-bcc6-11e6-8542-4a1bda5cd79f.png">

**Comment by sebj** [comment]
As far as I know, it's not possible for us to remove the Spotify icon from the notification.

(We're using a private API to set a big image on the left, but that forces the app icon to be next to the title – if you play a song in iTunes you'll notice its notification looks the same as ours).

**Comment by citruspi** [comment]
FWIW the private API for `NSUserNotification` is documented [here][0], if you figure out someway to optionally hide the app icon completely, feel free to re-open the issue.


[0]: https://github.com/indragiek/NSUserNotificationPrivate

**Comment by sebj** [comment]
@citruspi Aye, I looked through but it doesn't seem like there's anything of use on this issue (let me know if I missed something)

**Comment by citruspi** [comment]
@sebj Yep, I took a look and didn't see anything useful either. That was more for @rpanachi's benefit in case he was interested in looking into the matter and wanted a place to start.
