### ISSUE TITLE
Start Spotify-Notifications on Spotify start

### ISSUE THREAD

**Issue by Dalibor22x** [citruspi/Spotify-Notifications#79]
It would be great if Spotify-Notifications would be able to launch when Spotify starts in addition to the launch at start option.

**Comment by robinnorth** [comment]
Hey @Dalibor22x, have you tried using Automator to create a launcher that starts both Spotify and Spotify Notifications? See http://apple.stackexchange.com/a/153324 for an example.

**Comment by Dalibor22x** [comment]
Hey @robinnorth , haven't thought about that and I think I will use this solution, but it would be great if it would be a built-in option.

**Comment by sebj** [comment]
Is it necessary to have Spotify Notifications launch only when Spotify is launched vs launching at login? Seems there's very little difference – the app is very lightweight.

To have Spotify Notifications 'launch' (show in menubar) when Spotify launches would require a background process to check when Spotify is opened, meaning no matter whether you choose Launch At Login or Launch with Spotify, there'll be a process running.

Another solution (/ @robinnorth) would be to use [ControlPlane](https://www.controlplaneapp.com) to launch Spotify Notifications (`action`) whenever Spotify is opened (`context`/`rule`), which is actually what I currently do.

**Comment by citruspi** [comment]
Yep, I'd agree with @sebj and @robinnorth - using [ControlPlane][0] or an Automator application would probably be the way to go.

Another option - assuming you're comfortable scripting - would be to use [HammerSpoon][1] to watch for the launch of Spotify (using [`hs.application.watcher`][2]) and then launch Spotify Notifications (using [`hs.application`][3]).

Like @sebj said, any solution which is _native_ to Spotify Notifications would require some sort of daemon which runs on launch, watching for the start of the Spotify application. It's extremely unlikely that a solution like that would be merged in.

[0]: https://www.controlplaneapp.com/
[1]: http://www.hammerspoon.org
[2]: http://www.hammerspoon.org/docs/hs.application.watcher.html#start
[3]: http://www.hammerspoon.org/docs/hs.application.html

**Comment by Dalibor22x** [comment]
@sebj @citruspi Ok I see, the best solution would be to use Automator as @robinnorth mentioned.
