### ISSUE TITLE
Enhancement: Close button in preferences menu

### ISSUE THREAD

**Issue by JackWa** [citruspi/Spotify-Notifications#83]
Hey all,

Requesting a small Quality of Life change.
Could you add a Close button in addition to the Quit button?

I find myself hitting quit accidentally after making changes to my preferences.

Thank you.

**Comment by sebj** [comment]
Hi,

I've actually removed the buttons at the bottom of the preferences window entirely in the development branch (Website/Source/Contributors moved to About window; Quit now just in the menubar menu and not in the preferences window).
