### ISSUE TITLE
504 error on link

### ISSUE THREAD

**Issue by RAS-2112** [citruspi/Spotify-Notifications#87]
Getting a 504 error when trying to access the link on the site. Please fix.

**Comment by citruspi** [comment]
[AWS S3 is currently down][0]:

> We continue to experience high error rates with S3 in US-EAST-1, which is impacting various AWS services. We are working hard at repairing S3, believe we understand root cause, and are working on implementing what we believe will remediate the issue.

[0]: https://status.aws.amazon.com

**Comment by citruspi** [comment]
It should be resolved.

> S3 object retrieval, listing and deletion are fully recovered now. We are still working to recover normal operations for adding new objects to S3.
