### ISSUE TITLE
I have to manually dismiss the notification

### ISSUE THREAD

**Issue by philiplangleyza** [citruspi/Spotify-Notifications#96]
On both Sierra and High Sierra, the notification doesn't go away after a few seconds. I have to manually dismiss it. This didn't happen on my last computer (same versions of apps).

My settings, attached.
![image](https://user-images.githubusercontent.com/33683775/32837371-f82a805c-ca15-11e7-9ed6-44c616a83593.png)

**Comment by kailan** [comment]
Check *System Preferences > Notifications* to ensure that you have "Banners" selected and not "Alerts".

![screen shot 2017-12-01 at 23 10 20](https://user-images.githubusercontent.com/3542064/33511667-e8b19d48-d6ec-11e7-871f-b48a805a3e11.png)

**Comment by philiplangleyza** [comment]
OMG, now I feel like an idiot. Thanks so much!

**Comment by sebj** [comment]
Looks like this problem has been solved! 😄 I'm closing this issue, but if there's any odd behaviour from the app in relation to notification dismissal, feel free to comment/re-open.
